version: '3.8'
services:

  db:
    image: postgres:latest
    container_name: intersection_db
    ports:
      - "32678:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
