services:
  db:
    image: postgres:latest
    container_name: db_intersection
    ports:
      - "5500:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - custom_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: intersection_app
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - custom_network


networks:
  custom_network:
    driver: bridge
